### ISSUE TITLE
Other filters?

### ISSUE THREAD

**Issue by tjasmin111** [everythingishacked/Stash#1]
Very interesting project, thank you. But can we do a filter to make nose smaller?

**Comment by fheisler** [comment]
I might look into something like [Snap filters](https://www.snapchat.com/create) for more detailed, specific camera filters that handle face morphing. This is project just meant as a simple example for using MediaPipe with a virtual camera!

**Comment by tjasmin111** [comment]
Thanks. But not using snap or insta filters. I want to implement it myself, maybe using mediapipe.

**Comment by fheisler** [comment]
Got it! I linked Snap because they do have a framework you can build your own custom filters on. It should be possible from scratch with something like MediaPipe as well. You'd want to work with their 478 [face landmarks](https://developers.google.com/mediapipe/solutions/vision/face_landmarker) to get the most detailed tracking.

**Comment by tjasmin111** [comment]
Right. I'm able to use the 478 landmakrs, but now I'm not sure how to use it for making nose smaller.

**Comment by fheisler** [comment]
MediaPipe will just do the tracking, so you would need something else to handle modifying the resulting image based on the found landmarks. You could use OpenCV or Python Wand to modify a portion of each frame. The math to do whatever specific transformation you're aiming for will be the hard part. Maybe something like https://docs.wand-py.org/en/0.6.11/guide/fx.html#implode

**Comment by tjasmin111** [comment]
Yeah that math is hard. I wish implode was getting x,y of the point. It only applies to the center of image which is weird
